name: dart_softcorp
description: Dart Proto files for internal Softcorp Projects
version: 0.1.3
homepage: https://github.com/softcorp-io/softcorp-proto
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  protobuf: ^2.0.0
  grpc: ^3.0.2
  fixnum: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
