// source: softcorp.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.Softcorp.AdminUserRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.Softcorp.User');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Softcorp.AdminUserRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Softcorp.AdminUserRequest.repeatedFields_, null);
};
goog.inherits(proto.Softcorp.AdminUserRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Softcorp.AdminUserRequest.displayName = 'proto.Softcorp.AdminUserRequest';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Softcorp.AdminUserRequest.repeatedFields_ = [3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Softcorp.AdminUserRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Softcorp.AdminUserRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Softcorp.AdminUserRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Softcorp.AdminUserRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    userid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    email: jspb.Message.getFieldWithDefault(msg, 2, ""),
    idsList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    emailsList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
    decrypt: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    user: (f = msg.getUser()) && proto.Softcorp.User.toObject(includeInstance, f),
    overwriteid: jspb.Message.getBooleanFieldWithDefault(msg, 7, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Softcorp.AdminUserRequest}
 */
proto.Softcorp.AdminUserRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Softcorp.AdminUserRequest;
  return proto.Softcorp.AdminUserRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Softcorp.AdminUserRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Softcorp.AdminUserRequest}
 */
proto.Softcorp.AdminUserRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addIds(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addEmails(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDecrypt(value);
      break;
    case 6:
      var value = new proto.Softcorp.User;
      reader.readMessage(value,proto.Softcorp.User.deserializeBinaryFromReader);
      msg.setUser(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setOverwriteid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Softcorp.AdminUserRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Softcorp.AdminUserRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Softcorp.AdminUserRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Softcorp.AdminUserRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getIdsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getEmailsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
  f = message.getDecrypt();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getUser();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.Softcorp.User.serializeBinaryToWriter
    );
  }
  f = message.getOverwriteid();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
};


/**
 * optional string userId = 1;
 * @return {string}
 */
proto.Softcorp.AdminUserRequest.prototype.getUserid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Softcorp.AdminUserRequest} returns this
 */
proto.Softcorp.AdminUserRequest.prototype.setUserid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string email = 2;
 * @return {string}
 */
proto.Softcorp.AdminUserRequest.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Softcorp.AdminUserRequest} returns this
 */
proto.Softcorp.AdminUserRequest.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string ids = 3;
 * @return {!Array<string>}
 */
proto.Softcorp.AdminUserRequest.prototype.getIdsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.Softcorp.AdminUserRequest} returns this
 */
proto.Softcorp.AdminUserRequest.prototype.setIdsList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.Softcorp.AdminUserRequest} returns this
 */
proto.Softcorp.AdminUserRequest.prototype.addIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Softcorp.AdminUserRequest} returns this
 */
proto.Softcorp.AdminUserRequest.prototype.clearIdsList = function() {
  return this.setIdsList([]);
};


/**
 * repeated string emails = 4;
 * @return {!Array<string>}
 */
proto.Softcorp.AdminUserRequest.prototype.getEmailsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.Softcorp.AdminUserRequest} returns this
 */
proto.Softcorp.AdminUserRequest.prototype.setEmailsList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.Softcorp.AdminUserRequest} returns this
 */
proto.Softcorp.AdminUserRequest.prototype.addEmails = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Softcorp.AdminUserRequest} returns this
 */
proto.Softcorp.AdminUserRequest.prototype.clearEmailsList = function() {
  return this.setEmailsList([]);
};


/**
 * optional bool decrypt = 5;
 * @return {boolean}
 */
proto.Softcorp.AdminUserRequest.prototype.getDecrypt = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Softcorp.AdminUserRequest} returns this
 */
proto.Softcorp.AdminUserRequest.prototype.setDecrypt = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional User user = 6;
 * @return {?proto.Softcorp.User}
 */
proto.Softcorp.AdminUserRequest.prototype.getUser = function() {
  return /** @type{?proto.Softcorp.User} */ (
    jspb.Message.getWrapperField(this, proto.Softcorp.User, 6));
};


/**
 * @param {?proto.Softcorp.User|undefined} value
 * @return {!proto.Softcorp.AdminUserRequest} returns this
*/
proto.Softcorp.AdminUserRequest.prototype.setUser = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Softcorp.AdminUserRequest} returns this
 */
proto.Softcorp.AdminUserRequest.prototype.clearUser = function() {
  return this.setUser(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Softcorp.AdminUserRequest.prototype.hasUser = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional bool overwriteId = 7;
 * @return {boolean}
 */
proto.Softcorp.AdminUserRequest.prototype.getOverwriteid = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Softcorp.AdminUserRequest} returns this
 */
proto.Softcorp.AdminUserRequest.prototype.setOverwriteid = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


