// source: softcorp.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.Softcorp.ConnectAdminResponse');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Map');
goog.require('jspb.Message');
goog.require('proto.Softcorp.ClientApp');
goog.require('proto.Softcorp.ConnectMetrics');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Softcorp.ConnectAdminResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Softcorp.ConnectAdminResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Softcorp.ConnectAdminResponse.displayName = 'proto.Softcorp.ConnectAdminResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Softcorp.ConnectAdminResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.Softcorp.ConnectAdminResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Softcorp.ConnectAdminResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Softcorp.ConnectAdminResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    app: (f = msg.getApp()) && proto.Softcorp.ClientApp.toObject(includeInstance, f),
    metricsMap: (f = msg.getMetricsMap()) ? f.toObject(includeInstance, proto.Softcorp.ConnectMetrics.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Softcorp.ConnectAdminResponse}
 */
proto.Softcorp.ConnectAdminResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Softcorp.ConnectAdminResponse;
  return proto.Softcorp.ConnectAdminResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Softcorp.ConnectAdminResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Softcorp.ConnectAdminResponse}
 */
proto.Softcorp.ConnectAdminResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.Softcorp.ClientApp;
      reader.readMessage(value,proto.Softcorp.ClientApp.deserializeBinaryFromReader);
      msg.setApp(value);
      break;
    case 2:
      var value = msg.getMetricsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt32, jspb.BinaryReader.prototype.readMessage, proto.Softcorp.ConnectMetrics.deserializeBinaryFromReader, 0, new proto.Softcorp.ConnectMetrics());
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Softcorp.ConnectAdminResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Softcorp.ConnectAdminResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Softcorp.ConnectAdminResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Softcorp.ConnectAdminResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getApp();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.Softcorp.ClientApp.serializeBinaryToWriter
    );
  }
  f = message.getMetricsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeInt32, jspb.BinaryWriter.prototype.writeMessage, proto.Softcorp.ConnectMetrics.serializeBinaryToWriter);
  }
};


/**
 * optional ClientApp app = 1;
 * @return {?proto.Softcorp.ClientApp}
 */
proto.Softcorp.ConnectAdminResponse.prototype.getApp = function() {
  return /** @type{?proto.Softcorp.ClientApp} */ (
    jspb.Message.getWrapperField(this, proto.Softcorp.ClientApp, 1));
};


/**
 * @param {?proto.Softcorp.ClientApp|undefined} value
 * @return {!proto.Softcorp.ConnectAdminResponse} returns this
*/
proto.Softcorp.ConnectAdminResponse.prototype.setApp = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Softcorp.ConnectAdminResponse} returns this
 */
proto.Softcorp.ConnectAdminResponse.prototype.clearApp = function() {
  return this.setApp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Softcorp.ConnectAdminResponse.prototype.hasApp = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * map<int32, ConnectMetrics> metrics = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,!proto.Softcorp.ConnectMetrics>}
 */
proto.Softcorp.ConnectAdminResponse.prototype.getMetricsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,!proto.Softcorp.ConnectMetrics>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      proto.Softcorp.ConnectMetrics));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.Softcorp.ConnectAdminResponse} returns this
 */
proto.Softcorp.ConnectAdminResponse.prototype.clearMetricsMap = function() {
  this.getMetricsMap().clear();
  return this;};


