// source: softcorp.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.Softcorp.PublicDashboardRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.Softcorp.ClientApp');
goog.require('proto.Softcorp.Collaboration');
goog.require('proto.Softcorp.Organization');

goog.forwardDeclare('proto.Softcorp.Timespan');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Softcorp.PublicDashboardRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Softcorp.PublicDashboardRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Softcorp.PublicDashboardRequest.displayName = 'proto.Softcorp.PublicDashboardRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Softcorp.PublicDashboardRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Softcorp.PublicDashboardRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Softcorp.PublicDashboardRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Softcorp.PublicDashboardRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    accesstoken: jspb.Message.getFieldWithDefault(msg, 1, ""),
    organization: (f = msg.getOrganization()) && proto.Softcorp.Organization.toObject(includeInstance, f),
    connectapp: (f = msg.getConnectapp()) && proto.Softcorp.ClientApp.toObject(includeInstance, f),
    timespan: jspb.Message.getFieldWithDefault(msg, 4, 0),
    collaboration: (f = msg.getCollaboration()) && proto.Softcorp.Collaboration.toObject(includeInstance, f),
    secret: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Softcorp.PublicDashboardRequest}
 */
proto.Softcorp.PublicDashboardRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Softcorp.PublicDashboardRequest;
  return proto.Softcorp.PublicDashboardRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Softcorp.PublicDashboardRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Softcorp.PublicDashboardRequest}
 */
proto.Softcorp.PublicDashboardRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccesstoken(value);
      break;
    case 2:
      var value = new proto.Softcorp.Organization;
      reader.readMessage(value,proto.Softcorp.Organization.deserializeBinaryFromReader);
      msg.setOrganization(value);
      break;
    case 3:
      var value = new proto.Softcorp.ClientApp;
      reader.readMessage(value,proto.Softcorp.ClientApp.deserializeBinaryFromReader);
      msg.setConnectapp(value);
      break;
    case 4:
      var value = /** @type {!proto.Softcorp.Timespan} */ (reader.readEnum());
      msg.setTimespan(value);
      break;
    case 5:
      var value = new proto.Softcorp.Collaboration;
      reader.readMessage(value,proto.Softcorp.Collaboration.deserializeBinaryFromReader);
      msg.setCollaboration(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setSecret(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Softcorp.PublicDashboardRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Softcorp.PublicDashboardRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Softcorp.PublicDashboardRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Softcorp.PublicDashboardRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAccesstoken();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOrganization();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.Softcorp.Organization.serializeBinaryToWriter
    );
  }
  f = message.getConnectapp();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.Softcorp.ClientApp.serializeBinaryToWriter
    );
  }
  f = message.getTimespan();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getCollaboration();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.Softcorp.Collaboration.serializeBinaryToWriter
    );
  }
  f = message.getSecret();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional string accessToken = 1;
 * @return {string}
 */
proto.Softcorp.PublicDashboardRequest.prototype.getAccesstoken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Softcorp.PublicDashboardRequest} returns this
 */
proto.Softcorp.PublicDashboardRequest.prototype.setAccesstoken = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Organization organization = 2;
 * @return {?proto.Softcorp.Organization}
 */
proto.Softcorp.PublicDashboardRequest.prototype.getOrganization = function() {
  return /** @type{?proto.Softcorp.Organization} */ (
    jspb.Message.getWrapperField(this, proto.Softcorp.Organization, 2));
};


/**
 * @param {?proto.Softcorp.Organization|undefined} value
 * @return {!proto.Softcorp.PublicDashboardRequest} returns this
*/
proto.Softcorp.PublicDashboardRequest.prototype.setOrganization = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Softcorp.PublicDashboardRequest} returns this
 */
proto.Softcorp.PublicDashboardRequest.prototype.clearOrganization = function() {
  return this.setOrganization(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Softcorp.PublicDashboardRequest.prototype.hasOrganization = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional ClientApp connectApp = 3;
 * @return {?proto.Softcorp.ClientApp}
 */
proto.Softcorp.PublicDashboardRequest.prototype.getConnectapp = function() {
  return /** @type{?proto.Softcorp.ClientApp} */ (
    jspb.Message.getWrapperField(this, proto.Softcorp.ClientApp, 3));
};


/**
 * @param {?proto.Softcorp.ClientApp|undefined} value
 * @return {!proto.Softcorp.PublicDashboardRequest} returns this
*/
proto.Softcorp.PublicDashboardRequest.prototype.setConnectapp = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Softcorp.PublicDashboardRequest} returns this
 */
proto.Softcorp.PublicDashboardRequest.prototype.clearConnectapp = function() {
  return this.setConnectapp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Softcorp.PublicDashboardRequest.prototype.hasConnectapp = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Timespan timespan = 4;
 * @return {!proto.Softcorp.Timespan}
 */
proto.Softcorp.PublicDashboardRequest.prototype.getTimespan = function() {
  return /** @type {!proto.Softcorp.Timespan} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.Softcorp.Timespan} value
 * @return {!proto.Softcorp.PublicDashboardRequest} returns this
 */
proto.Softcorp.PublicDashboardRequest.prototype.setTimespan = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional Collaboration collaboration = 5;
 * @return {?proto.Softcorp.Collaboration}
 */
proto.Softcorp.PublicDashboardRequest.prototype.getCollaboration = function() {
  return /** @type{?proto.Softcorp.Collaboration} */ (
    jspb.Message.getWrapperField(this, proto.Softcorp.Collaboration, 5));
};


/**
 * @param {?proto.Softcorp.Collaboration|undefined} value
 * @return {!proto.Softcorp.PublicDashboardRequest} returns this
*/
proto.Softcorp.PublicDashboardRequest.prototype.setCollaboration = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Softcorp.PublicDashboardRequest} returns this
 */
proto.Softcorp.PublicDashboardRequest.prototype.clearCollaboration = function() {
  return this.setCollaboration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Softcorp.PublicDashboardRequest.prototype.hasCollaboration = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional string secret = 6;
 * @return {string}
 */
proto.Softcorp.PublicDashboardRequest.prototype.getSecret = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.Softcorp.PublicDashboardRequest} returns this
 */
proto.Softcorp.PublicDashboardRequest.prototype.setSecret = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


