// source: softcorp.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.Softcorp.AdminCollaborationResponse');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.Softcorp.Collaboration');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Softcorp.AdminCollaborationResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Softcorp.AdminCollaborationResponse.repeatedFields_, null);
};
goog.inherits(proto.Softcorp.AdminCollaborationResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Softcorp.AdminCollaborationResponse.displayName = 'proto.Softcorp.AdminCollaborationResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Softcorp.AdminCollaborationResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Softcorp.AdminCollaborationResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.Softcorp.AdminCollaborationResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Softcorp.AdminCollaborationResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Softcorp.AdminCollaborationResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    collaboration: (f = msg.getCollaboration()) && proto.Softcorp.Collaboration.toObject(includeInstance, f),
    collaborationsList: jspb.Message.toObjectList(msg.getCollaborationsList(),
    proto.Softcorp.Collaboration.toObject, includeInstance),
    secret: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Softcorp.AdminCollaborationResponse}
 */
proto.Softcorp.AdminCollaborationResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Softcorp.AdminCollaborationResponse;
  return proto.Softcorp.AdminCollaborationResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Softcorp.AdminCollaborationResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Softcorp.AdminCollaborationResponse}
 */
proto.Softcorp.AdminCollaborationResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.Softcorp.Collaboration;
      reader.readMessage(value,proto.Softcorp.Collaboration.deserializeBinaryFromReader);
      msg.setCollaboration(value);
      break;
    case 2:
      var value = new proto.Softcorp.Collaboration;
      reader.readMessage(value,proto.Softcorp.Collaboration.deserializeBinaryFromReader);
      msg.addCollaborations(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSecret(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Softcorp.AdminCollaborationResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Softcorp.AdminCollaborationResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Softcorp.AdminCollaborationResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Softcorp.AdminCollaborationResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCollaboration();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.Softcorp.Collaboration.serializeBinaryToWriter
    );
  }
  f = message.getCollaborationsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.Softcorp.Collaboration.serializeBinaryToWriter
    );
  }
  f = message.getSecret();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional Collaboration collaboration = 1;
 * @return {?proto.Softcorp.Collaboration}
 */
proto.Softcorp.AdminCollaborationResponse.prototype.getCollaboration = function() {
  return /** @type{?proto.Softcorp.Collaboration} */ (
    jspb.Message.getWrapperField(this, proto.Softcorp.Collaboration, 1));
};


/**
 * @param {?proto.Softcorp.Collaboration|undefined} value
 * @return {!proto.Softcorp.AdminCollaborationResponse} returns this
*/
proto.Softcorp.AdminCollaborationResponse.prototype.setCollaboration = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Softcorp.AdminCollaborationResponse} returns this
 */
proto.Softcorp.AdminCollaborationResponse.prototype.clearCollaboration = function() {
  return this.setCollaboration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Softcorp.AdminCollaborationResponse.prototype.hasCollaboration = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Collaboration collaborations = 2;
 * @return {!Array<!proto.Softcorp.Collaboration>}
 */
proto.Softcorp.AdminCollaborationResponse.prototype.getCollaborationsList = function() {
  return /** @type{!Array<!proto.Softcorp.Collaboration>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Softcorp.Collaboration, 2));
};


/**
 * @param {!Array<!proto.Softcorp.Collaboration>} value
 * @return {!proto.Softcorp.AdminCollaborationResponse} returns this
*/
proto.Softcorp.AdminCollaborationResponse.prototype.setCollaborationsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.Softcorp.Collaboration=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Softcorp.Collaboration}
 */
proto.Softcorp.AdminCollaborationResponse.prototype.addCollaborations = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.Softcorp.Collaboration, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Softcorp.AdminCollaborationResponse} returns this
 */
proto.Softcorp.AdminCollaborationResponse.prototype.clearCollaborationsList = function() {
  return this.setCollaborationsList([]);
};


/**
 * optional string secret = 3;
 * @return {string}
 */
proto.Softcorp.AdminCollaborationResponse.prototype.getSecret = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Softcorp.AdminCollaborationResponse} returns this
 */
proto.Softcorp.AdminCollaborationResponse.prototype.setSecret = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


