// source: softcorp.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.Softcorp.AuthPublicRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.Softcorp.SsnProvider');

goog.forwardDeclare('proto.Softcorp.Gender');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Softcorp.AuthPublicRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Softcorp.AuthPublicRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Softcorp.AuthPublicRequest.displayName = 'proto.Softcorp.AuthPublicRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Softcorp.AuthPublicRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Softcorp.AuthPublicRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Softcorp.AuthPublicRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Softcorp.AuthPublicRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    challenge: jspb.Message.getFieldWithDefault(msg, 1, ""),
    email: jspb.Message.getFieldWithDefault(msg, 2, ""),
    password: jspb.Message.getFieldWithDefault(msg, 3, ""),
    gender: jspb.Message.getFieldWithDefault(msg, 4, 0),
    consent: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
    jwtidtoken: jspb.Message.getFieldWithDefault(msg, 6, ""),
    ssnprovider: (f = msg.getSsnprovider()) && proto.Softcorp.SsnProvider.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Softcorp.AuthPublicRequest}
 */
proto.Softcorp.AuthPublicRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Softcorp.AuthPublicRequest;
  return proto.Softcorp.AuthPublicRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Softcorp.AuthPublicRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Softcorp.AuthPublicRequest}
 */
proto.Softcorp.AuthPublicRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setChallenge(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPassword(value);
      break;
    case 4:
      var value = /** @type {!proto.Softcorp.Gender} */ (reader.readEnum());
      msg.setGender(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setConsent(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setJwtidtoken(value);
      break;
    case 7:
      var value = new proto.Softcorp.SsnProvider;
      reader.readMessage(value,proto.Softcorp.SsnProvider.deserializeBinaryFromReader);
      msg.setSsnprovider(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Softcorp.AuthPublicRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Softcorp.AuthPublicRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Softcorp.AuthPublicRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Softcorp.AuthPublicRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getChallenge();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPassword();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getGender();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getConsent();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getJwtidtoken();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getSsnprovider();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.Softcorp.SsnProvider.serializeBinaryToWriter
    );
  }
};


/**
 * optional string challenge = 1;
 * @return {string}
 */
proto.Softcorp.AuthPublicRequest.prototype.getChallenge = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Softcorp.AuthPublicRequest} returns this
 */
proto.Softcorp.AuthPublicRequest.prototype.setChallenge = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string email = 2;
 * @return {string}
 */
proto.Softcorp.AuthPublicRequest.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Softcorp.AuthPublicRequest} returns this
 */
proto.Softcorp.AuthPublicRequest.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string password = 3;
 * @return {string}
 */
proto.Softcorp.AuthPublicRequest.prototype.getPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Softcorp.AuthPublicRequest} returns this
 */
proto.Softcorp.AuthPublicRequest.prototype.setPassword = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional Gender gender = 4;
 * @return {!proto.Softcorp.Gender}
 */
proto.Softcorp.AuthPublicRequest.prototype.getGender = function() {
  return /** @type {!proto.Softcorp.Gender} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.Softcorp.Gender} value
 * @return {!proto.Softcorp.AuthPublicRequest} returns this
 */
proto.Softcorp.AuthPublicRequest.prototype.setGender = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional bool consent = 5;
 * @return {boolean}
 */
proto.Softcorp.AuthPublicRequest.prototype.getConsent = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Softcorp.AuthPublicRequest} returns this
 */
proto.Softcorp.AuthPublicRequest.prototype.setConsent = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional string jwtIdToken = 6;
 * @return {string}
 */
proto.Softcorp.AuthPublicRequest.prototype.getJwtidtoken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.Softcorp.AuthPublicRequest} returns this
 */
proto.Softcorp.AuthPublicRequest.prototype.setJwtidtoken = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional SsnProvider ssnProvider = 7;
 * @return {?proto.Softcorp.SsnProvider}
 */
proto.Softcorp.AuthPublicRequest.prototype.getSsnprovider = function() {
  return /** @type{?proto.Softcorp.SsnProvider} */ (
    jspb.Message.getWrapperField(this, proto.Softcorp.SsnProvider, 7));
};


/**
 * @param {?proto.Softcorp.SsnProvider|undefined} value
 * @return {!proto.Softcorp.AuthPublicRequest} returns this
*/
proto.Softcorp.AuthPublicRequest.prototype.setSsnprovider = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Softcorp.AuthPublicRequest} returns this
 */
proto.Softcorp.AuthPublicRequest.prototype.clearSsnprovider = function() {
  return this.setSsnprovider(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Softcorp.AuthPublicRequest.prototype.hasSsnprovider = function() {
  return jspb.Message.getField(this, 7) != null;
};


