// source: softcorp.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.Softcorp.ClientApp');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.Softcorp.ClientMetadata');
goog.require('proto.Softcorp.CountryCode');
goog.require('proto.Softcorp.Grant');
goog.require('proto.Softcorp.OauthResponse');
goog.require('proto.Softcorp.Scope');
goog.require('proto.google.protobuf.Timestamp');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Softcorp.ClientApp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Softcorp.ClientApp.repeatedFields_, null);
};
goog.inherits(proto.Softcorp.ClientApp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Softcorp.ClientApp.displayName = 'proto.Softcorp.ClientApp';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Softcorp.ClientApp.repeatedFields_ = [10,11,12,13,14,17,18,19,20,21];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Softcorp.ClientApp.prototype.toObject = function(opt_includeInstance) {
  return proto.Softcorp.ClientApp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Softcorp.ClientApp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Softcorp.ClientApp.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    password: jspb.Message.getFieldWithDefault(msg, 3, ""),
    contactemail: jspb.Message.getFieldWithDefault(msg, 4, ""),
    ownerid: jspb.Message.getFieldWithDefault(msg, 5, ""),
    appwebsite: jspb.Message.getFieldWithDefault(msg, 6, ""),
    logourl: jspb.Message.getFieldWithDefault(msg, 7, ""),
    termsurl: jspb.Message.getFieldWithDefault(msg, 8, ""),
    clientmetadata: (f = msg.getClientmetadata()) && proto.Softcorp.ClientMetadata.toObject(includeInstance, f),
    audienceList: (f = jspb.Message.getRepeatedField(msg, 10)) == null ? undefined : f,
    scopesList: jspb.Message.toObjectList(msg.getScopesList(),
    proto.Softcorp.Scope.toObject, includeInstance),
    grantsList: jspb.Message.toObjectList(msg.getGrantsList(),
    proto.Softcorp.Grant.toObject, includeInstance),
    responsesList: jspb.Message.toObjectList(msg.getResponsesList(),
    proto.Softcorp.OauthResponse.toObject, includeInstance),
    callbacksList: (f = jspb.Message.getRepeatedField(msg, 14)) == null ? undefined : f,
    createdat: (f = msg.getCreatedat()) && proto.google.protobuf.Timestamp.toObject(includeInstance, f),
    updatedat: (f = msg.getUpdatedat()) && proto.google.protobuf.Timestamp.toObject(includeInstance, f),
    availablescopesList: jspb.Message.toObjectList(msg.getAvailablescopesList(),
    proto.Softcorp.Scope.toObject, includeInstance),
    availablegrantsList: jspb.Message.toObjectList(msg.getAvailablegrantsList(),
    proto.Softcorp.Grant.toObject, includeInstance),
    availableresponsesList: jspb.Message.toObjectList(msg.getAvailableresponsesList(),
    proto.Softcorp.OauthResponse.toObject, includeInstance),
    availablecountriesList: jspb.Message.toObjectList(msg.getAvailablecountriesList(),
    proto.Softcorp.CountryCode.toObject, includeInstance),
    advancedscopesList: jspb.Message.toObjectList(msg.getAdvancedscopesList(),
    proto.Softcorp.Scope.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Softcorp.ClientApp}
 */
proto.Softcorp.ClientApp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Softcorp.ClientApp;
  return proto.Softcorp.ClientApp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Softcorp.ClientApp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Softcorp.ClientApp}
 */
proto.Softcorp.ClientApp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPassword(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setContactemail(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setOwnerid(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setAppwebsite(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setLogourl(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setTermsurl(value);
      break;
    case 9:
      var value = new proto.Softcorp.ClientMetadata;
      reader.readMessage(value,proto.Softcorp.ClientMetadata.deserializeBinaryFromReader);
      msg.setClientmetadata(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.addAudience(value);
      break;
    case 11:
      var value = new proto.Softcorp.Scope;
      reader.readMessage(value,proto.Softcorp.Scope.deserializeBinaryFromReader);
      msg.addScopes(value);
      break;
    case 12:
      var value = new proto.Softcorp.Grant;
      reader.readMessage(value,proto.Softcorp.Grant.deserializeBinaryFromReader);
      msg.addGrants(value);
      break;
    case 13:
      var value = new proto.Softcorp.OauthResponse;
      reader.readMessage(value,proto.Softcorp.OauthResponse.deserializeBinaryFromReader);
      msg.addResponses(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.addCallbacks(value);
      break;
    case 15:
      var value = new proto.google.protobuf.Timestamp;
      reader.readMessage(value,proto.google.protobuf.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedat(value);
      break;
    case 16:
      var value = new proto.google.protobuf.Timestamp;
      reader.readMessage(value,proto.google.protobuf.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedat(value);
      break;
    case 17:
      var value = new proto.Softcorp.Scope;
      reader.readMessage(value,proto.Softcorp.Scope.deserializeBinaryFromReader);
      msg.addAvailablescopes(value);
      break;
    case 18:
      var value = new proto.Softcorp.Grant;
      reader.readMessage(value,proto.Softcorp.Grant.deserializeBinaryFromReader);
      msg.addAvailablegrants(value);
      break;
    case 19:
      var value = new proto.Softcorp.OauthResponse;
      reader.readMessage(value,proto.Softcorp.OauthResponse.deserializeBinaryFromReader);
      msg.addAvailableresponses(value);
      break;
    case 20:
      var value = new proto.Softcorp.CountryCode;
      reader.readMessage(value,proto.Softcorp.CountryCode.deserializeBinaryFromReader);
      msg.addAvailablecountries(value);
      break;
    case 21:
      var value = new proto.Softcorp.Scope;
      reader.readMessage(value,proto.Softcorp.Scope.deserializeBinaryFromReader);
      msg.addAdvancedscopes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Softcorp.ClientApp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Softcorp.ClientApp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Softcorp.ClientApp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Softcorp.ClientApp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPassword();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getContactemail();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getOwnerid();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getAppwebsite();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getLogourl();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getTermsurl();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getClientmetadata();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.Softcorp.ClientMetadata.serializeBinaryToWriter
    );
  }
  f = message.getAudienceList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      10,
      f
    );
  }
  f = message.getScopesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      proto.Softcorp.Scope.serializeBinaryToWriter
    );
  }
  f = message.getGrantsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      12,
      f,
      proto.Softcorp.Grant.serializeBinaryToWriter
    );
  }
  f = message.getResponsesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      13,
      f,
      proto.Softcorp.OauthResponse.serializeBinaryToWriter
    );
  }
  f = message.getCallbacksList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      14,
      f
    );
  }
  f = message.getCreatedat();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      proto.google.protobuf.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedat();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      proto.google.protobuf.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getAvailablescopesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      17,
      f,
      proto.Softcorp.Scope.serializeBinaryToWriter
    );
  }
  f = message.getAvailablegrantsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      18,
      f,
      proto.Softcorp.Grant.serializeBinaryToWriter
    );
  }
  f = message.getAvailableresponsesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      19,
      f,
      proto.Softcorp.OauthResponse.serializeBinaryToWriter
    );
  }
  f = message.getAvailablecountriesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      20,
      f,
      proto.Softcorp.CountryCode.serializeBinaryToWriter
    );
  }
  f = message.getAdvancedscopesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      21,
      f,
      proto.Softcorp.Scope.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.Softcorp.ClientApp.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Softcorp.ClientApp} returns this
 */
proto.Softcorp.ClientApp.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.Softcorp.ClientApp.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Softcorp.ClientApp} returns this
 */
proto.Softcorp.ClientApp.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string password = 3;
 * @return {string}
 */
proto.Softcorp.ClientApp.prototype.getPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Softcorp.ClientApp} returns this
 */
proto.Softcorp.ClientApp.prototype.setPassword = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string contactEmail = 4;
 * @return {string}
 */
proto.Softcorp.ClientApp.prototype.getContactemail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.Softcorp.ClientApp} returns this
 */
proto.Softcorp.ClientApp.prototype.setContactemail = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string ownerId = 5;
 * @return {string}
 */
proto.Softcorp.ClientApp.prototype.getOwnerid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.Softcorp.ClientApp} returns this
 */
proto.Softcorp.ClientApp.prototype.setOwnerid = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string appWebsite = 6;
 * @return {string}
 */
proto.Softcorp.ClientApp.prototype.getAppwebsite = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.Softcorp.ClientApp} returns this
 */
proto.Softcorp.ClientApp.prototype.setAppwebsite = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string logoUrl = 7;
 * @return {string}
 */
proto.Softcorp.ClientApp.prototype.getLogourl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.Softcorp.ClientApp} returns this
 */
proto.Softcorp.ClientApp.prototype.setLogourl = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string termsUrl = 8;
 * @return {string}
 */
proto.Softcorp.ClientApp.prototype.getTermsurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.Softcorp.ClientApp} returns this
 */
proto.Softcorp.ClientApp.prototype.setTermsurl = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional ClientMetadata clientMetadata = 9;
 * @return {?proto.Softcorp.ClientMetadata}
 */
proto.Softcorp.ClientApp.prototype.getClientmetadata = function() {
  return /** @type{?proto.Softcorp.ClientMetadata} */ (
    jspb.Message.getWrapperField(this, proto.Softcorp.ClientMetadata, 9));
};


/**
 * @param {?proto.Softcorp.ClientMetadata|undefined} value
 * @return {!proto.Softcorp.ClientApp} returns this
*/
proto.Softcorp.ClientApp.prototype.setClientmetadata = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Softcorp.ClientApp} returns this
 */
proto.Softcorp.ClientApp.prototype.clearClientmetadata = function() {
  return this.setClientmetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Softcorp.ClientApp.prototype.hasClientmetadata = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * repeated string audience = 10;
 * @return {!Array<string>}
 */
proto.Softcorp.ClientApp.prototype.getAudienceList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 10));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.Softcorp.ClientApp} returns this
 */
proto.Softcorp.ClientApp.prototype.setAudienceList = function(value) {
  return jspb.Message.setField(this, 10, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.Softcorp.ClientApp} returns this
 */
proto.Softcorp.ClientApp.prototype.addAudience = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 10, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Softcorp.ClientApp} returns this
 */
proto.Softcorp.ClientApp.prototype.clearAudienceList = function() {
  return this.setAudienceList([]);
};


/**
 * repeated Scope scopes = 11;
 * @return {!Array<!proto.Softcorp.Scope>}
 */
proto.Softcorp.ClientApp.prototype.getScopesList = function() {
  return /** @type{!Array<!proto.Softcorp.Scope>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Softcorp.Scope, 11));
};


/**
 * @param {!Array<!proto.Softcorp.Scope>} value
 * @return {!proto.Softcorp.ClientApp} returns this
*/
proto.Softcorp.ClientApp.prototype.setScopesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 11, value);
};


/**
 * @param {!proto.Softcorp.Scope=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Softcorp.Scope}
 */
proto.Softcorp.ClientApp.prototype.addScopes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 11, opt_value, proto.Softcorp.Scope, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Softcorp.ClientApp} returns this
 */
proto.Softcorp.ClientApp.prototype.clearScopesList = function() {
  return this.setScopesList([]);
};


/**
 * repeated Grant grants = 12;
 * @return {!Array<!proto.Softcorp.Grant>}
 */
proto.Softcorp.ClientApp.prototype.getGrantsList = function() {
  return /** @type{!Array<!proto.Softcorp.Grant>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Softcorp.Grant, 12));
};


/**
 * @param {!Array<!proto.Softcorp.Grant>} value
 * @return {!proto.Softcorp.ClientApp} returns this
*/
proto.Softcorp.ClientApp.prototype.setGrantsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 12, value);
};


/**
 * @param {!proto.Softcorp.Grant=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Softcorp.Grant}
 */
proto.Softcorp.ClientApp.prototype.addGrants = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 12, opt_value, proto.Softcorp.Grant, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Softcorp.ClientApp} returns this
 */
proto.Softcorp.ClientApp.prototype.clearGrantsList = function() {
  return this.setGrantsList([]);
};


/**
 * repeated OauthResponse responses = 13;
 * @return {!Array<!proto.Softcorp.OauthResponse>}
 */
proto.Softcorp.ClientApp.prototype.getResponsesList = function() {
  return /** @type{!Array<!proto.Softcorp.OauthResponse>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Softcorp.OauthResponse, 13));
};


/**
 * @param {!Array<!proto.Softcorp.OauthResponse>} value
 * @return {!proto.Softcorp.ClientApp} returns this
*/
proto.Softcorp.ClientApp.prototype.setResponsesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 13, value);
};


/**
 * @param {!proto.Softcorp.OauthResponse=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Softcorp.OauthResponse}
 */
proto.Softcorp.ClientApp.prototype.addResponses = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 13, opt_value, proto.Softcorp.OauthResponse, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Softcorp.ClientApp} returns this
 */
proto.Softcorp.ClientApp.prototype.clearResponsesList = function() {
  return this.setResponsesList([]);
};


/**
 * repeated string callbacks = 14;
 * @return {!Array<string>}
 */
proto.Softcorp.ClientApp.prototype.getCallbacksList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 14));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.Softcorp.ClientApp} returns this
 */
proto.Softcorp.ClientApp.prototype.setCallbacksList = function(value) {
  return jspb.Message.setField(this, 14, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.Softcorp.ClientApp} returns this
 */
proto.Softcorp.ClientApp.prototype.addCallbacks = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 14, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Softcorp.ClientApp} returns this
 */
proto.Softcorp.ClientApp.prototype.clearCallbacksList = function() {
  return this.setCallbacksList([]);
};


/**
 * optional google.protobuf.Timestamp createdAt = 15;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.Softcorp.ClientApp.prototype.getCreatedat = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.Timestamp, 15));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.Softcorp.ClientApp} returns this
*/
proto.Softcorp.ClientApp.prototype.setCreatedat = function(value) {
  return jspb.Message.setWrapperField(this, 15, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Softcorp.ClientApp} returns this
 */
proto.Softcorp.ClientApp.prototype.clearCreatedat = function() {
  return this.setCreatedat(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Softcorp.ClientApp.prototype.hasCreatedat = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional google.protobuf.Timestamp updatedAt = 16;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.Softcorp.ClientApp.prototype.getUpdatedat = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.Timestamp, 16));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.Softcorp.ClientApp} returns this
*/
proto.Softcorp.ClientApp.prototype.setUpdatedat = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Softcorp.ClientApp} returns this
 */
proto.Softcorp.ClientApp.prototype.clearUpdatedat = function() {
  return this.setUpdatedat(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Softcorp.ClientApp.prototype.hasUpdatedat = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * repeated Scope availableScopes = 17;
 * @return {!Array<!proto.Softcorp.Scope>}
 */
proto.Softcorp.ClientApp.prototype.getAvailablescopesList = function() {
  return /** @type{!Array<!proto.Softcorp.Scope>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Softcorp.Scope, 17));
};


/**
 * @param {!Array<!proto.Softcorp.Scope>} value
 * @return {!proto.Softcorp.ClientApp} returns this
*/
proto.Softcorp.ClientApp.prototype.setAvailablescopesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 17, value);
};


/**
 * @param {!proto.Softcorp.Scope=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Softcorp.Scope}
 */
proto.Softcorp.ClientApp.prototype.addAvailablescopes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 17, opt_value, proto.Softcorp.Scope, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Softcorp.ClientApp} returns this
 */
proto.Softcorp.ClientApp.prototype.clearAvailablescopesList = function() {
  return this.setAvailablescopesList([]);
};


/**
 * repeated Grant availableGrants = 18;
 * @return {!Array<!proto.Softcorp.Grant>}
 */
proto.Softcorp.ClientApp.prototype.getAvailablegrantsList = function() {
  return /** @type{!Array<!proto.Softcorp.Grant>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Softcorp.Grant, 18));
};


/**
 * @param {!Array<!proto.Softcorp.Grant>} value
 * @return {!proto.Softcorp.ClientApp} returns this
*/
proto.Softcorp.ClientApp.prototype.setAvailablegrantsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 18, value);
};


/**
 * @param {!proto.Softcorp.Grant=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Softcorp.Grant}
 */
proto.Softcorp.ClientApp.prototype.addAvailablegrants = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 18, opt_value, proto.Softcorp.Grant, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Softcorp.ClientApp} returns this
 */
proto.Softcorp.ClientApp.prototype.clearAvailablegrantsList = function() {
  return this.setAvailablegrantsList([]);
};


/**
 * repeated OauthResponse availableResponses = 19;
 * @return {!Array<!proto.Softcorp.OauthResponse>}
 */
proto.Softcorp.ClientApp.prototype.getAvailableresponsesList = function() {
  return /** @type{!Array<!proto.Softcorp.OauthResponse>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Softcorp.OauthResponse, 19));
};


/**
 * @param {!Array<!proto.Softcorp.OauthResponse>} value
 * @return {!proto.Softcorp.ClientApp} returns this
*/
proto.Softcorp.ClientApp.prototype.setAvailableresponsesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 19, value);
};


/**
 * @param {!proto.Softcorp.OauthResponse=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Softcorp.OauthResponse}
 */
proto.Softcorp.ClientApp.prototype.addAvailableresponses = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 19, opt_value, proto.Softcorp.OauthResponse, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Softcorp.ClientApp} returns this
 */
proto.Softcorp.ClientApp.prototype.clearAvailableresponsesList = function() {
  return this.setAvailableresponsesList([]);
};


/**
 * repeated CountryCode availableCountries = 20;
 * @return {!Array<!proto.Softcorp.CountryCode>}
 */
proto.Softcorp.ClientApp.prototype.getAvailablecountriesList = function() {
  return /** @type{!Array<!proto.Softcorp.CountryCode>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Softcorp.CountryCode, 20));
};


/**
 * @param {!Array<!proto.Softcorp.CountryCode>} value
 * @return {!proto.Softcorp.ClientApp} returns this
*/
proto.Softcorp.ClientApp.prototype.setAvailablecountriesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 20, value);
};


/**
 * @param {!proto.Softcorp.CountryCode=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Softcorp.CountryCode}
 */
proto.Softcorp.ClientApp.prototype.addAvailablecountries = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 20, opt_value, proto.Softcorp.CountryCode, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Softcorp.ClientApp} returns this
 */
proto.Softcorp.ClientApp.prototype.clearAvailablecountriesList = function() {
  return this.setAvailablecountriesList([]);
};


/**
 * repeated Scope advancedScopes = 21;
 * @return {!Array<!proto.Softcorp.Scope>}
 */
proto.Softcorp.ClientApp.prototype.getAdvancedscopesList = function() {
  return /** @type{!Array<!proto.Softcorp.Scope>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Softcorp.Scope, 21));
};


/**
 * @param {!Array<!proto.Softcorp.Scope>} value
 * @return {!proto.Softcorp.ClientApp} returns this
*/
proto.Softcorp.ClientApp.prototype.setAdvancedscopesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 21, value);
};


/**
 * @param {!proto.Softcorp.Scope=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Softcorp.Scope}
 */
proto.Softcorp.ClientApp.prototype.addAdvancedscopes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 21, opt_value, proto.Softcorp.Scope, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Softcorp.ClientApp} returns this
 */
proto.Softcorp.ClientApp.prototype.clearAdvancedscopesList = function() {
  return this.setAdvancedscopesList([]);
};


