// source: softcorp.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.Softcorp.ClientMetadata');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.Softcorp.CountryCode');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Softcorp.ClientMetadata = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Softcorp.ClientMetadata.repeatedFields_, null);
};
goog.inherits(proto.Softcorp.ClientMetadata, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Softcorp.ClientMetadata.displayName = 'proto.Softcorp.ClientMetadata';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Softcorp.ClientMetadata.repeatedFields_ = [21,7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Softcorp.ClientMetadata.prototype.toObject = function(opt_includeInstance) {
  return proto.Softcorp.ClientMetadata.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Softcorp.ClientMetadata} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Softcorp.ClientMetadata.toObject = function(includeInstance, msg) {
  var f, obj = {
    isopen: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    allowedemailsList: (f = jspb.Message.getRepeatedField(msg, 21)) == null ? undefined : f,
    about: jspb.Message.getFieldWithDefault(msg, 3, ""),
    userownerid: jspb.Message.getFieldWithDefault(msg, 4, ""),
    agelowerlimit: jspb.Message.getFieldWithDefault(msg, 5, 0),
    ageupperlimit: jspb.Message.getFieldWithDefault(msg, 6, 0),
    allowedcountriesList: jspb.Message.toObjectList(msg.getAllowedcountriesList(),
    proto.Softcorp.CountryCode.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Softcorp.ClientMetadata}
 */
proto.Softcorp.ClientMetadata.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Softcorp.ClientMetadata;
  return proto.Softcorp.ClientMetadata.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Softcorp.ClientMetadata} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Softcorp.ClientMetadata}
 */
proto.Softcorp.ClientMetadata.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsopen(value);
      break;
    case 21:
      var value = /** @type {string} */ (reader.readString());
      msg.addAllowedemails(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAbout(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserownerid(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAgelowerlimit(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAgeupperlimit(value);
      break;
    case 7:
      var value = new proto.Softcorp.CountryCode;
      reader.readMessage(value,proto.Softcorp.CountryCode.deserializeBinaryFromReader);
      msg.addAllowedcountries(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Softcorp.ClientMetadata.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Softcorp.ClientMetadata.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Softcorp.ClientMetadata} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Softcorp.ClientMetadata.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIsopen();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getAllowedemailsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      21,
      f
    );
  }
  f = message.getAbout();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getUserownerid();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getAgelowerlimit();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getAgeupperlimit();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getAllowedcountriesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      proto.Softcorp.CountryCode.serializeBinaryToWriter
    );
  }
};


/**
 * optional bool isOpen = 1;
 * @return {boolean}
 */
proto.Softcorp.ClientMetadata.prototype.getIsopen = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Softcorp.ClientMetadata} returns this
 */
proto.Softcorp.ClientMetadata.prototype.setIsopen = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * repeated string allowedEmails = 21;
 * @return {!Array<string>}
 */
proto.Softcorp.ClientMetadata.prototype.getAllowedemailsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 21));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.Softcorp.ClientMetadata} returns this
 */
proto.Softcorp.ClientMetadata.prototype.setAllowedemailsList = function(value) {
  return jspb.Message.setField(this, 21, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.Softcorp.ClientMetadata} returns this
 */
proto.Softcorp.ClientMetadata.prototype.addAllowedemails = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 21, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Softcorp.ClientMetadata} returns this
 */
proto.Softcorp.ClientMetadata.prototype.clearAllowedemailsList = function() {
  return this.setAllowedemailsList([]);
};


/**
 * optional string about = 3;
 * @return {string}
 */
proto.Softcorp.ClientMetadata.prototype.getAbout = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Softcorp.ClientMetadata} returns this
 */
proto.Softcorp.ClientMetadata.prototype.setAbout = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string userOwnerId = 4;
 * @return {string}
 */
proto.Softcorp.ClientMetadata.prototype.getUserownerid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.Softcorp.ClientMetadata} returns this
 */
proto.Softcorp.ClientMetadata.prototype.setUserownerid = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 ageLowerLimit = 5;
 * @return {number}
 */
proto.Softcorp.ClientMetadata.prototype.getAgelowerlimit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.Softcorp.ClientMetadata} returns this
 */
proto.Softcorp.ClientMetadata.prototype.setAgelowerlimit = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 ageUpperLimit = 6;
 * @return {number}
 */
proto.Softcorp.ClientMetadata.prototype.getAgeupperlimit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.Softcorp.ClientMetadata} returns this
 */
proto.Softcorp.ClientMetadata.prototype.setAgeupperlimit = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * repeated CountryCode allowedCountries = 7;
 * @return {!Array<!proto.Softcorp.CountryCode>}
 */
proto.Softcorp.ClientMetadata.prototype.getAllowedcountriesList = function() {
  return /** @type{!Array<!proto.Softcorp.CountryCode>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Softcorp.CountryCode, 7));
};


/**
 * @param {!Array<!proto.Softcorp.CountryCode>} value
 * @return {!proto.Softcorp.ClientMetadata} returns this
*/
proto.Softcorp.ClientMetadata.prototype.setAllowedcountriesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.Softcorp.CountryCode=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Softcorp.CountryCode}
 */
proto.Softcorp.ClientMetadata.prototype.addAllowedcountries = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.Softcorp.CountryCode, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Softcorp.ClientMetadata} returns this
 */
proto.Softcorp.ClientMetadata.prototype.clearAllowedcountriesList = function() {
  return this.setAllowedcountriesList([]);
};


