// source: softcorp.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.Softcorp.ConnectAdminRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.Softcorp.ClientApp');

goog.forwardDeclare('proto.Softcorp.Timespan');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Softcorp.ConnectAdminRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Softcorp.ConnectAdminRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Softcorp.ConnectAdminRequest.displayName = 'proto.Softcorp.ConnectAdminRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Softcorp.ConnectAdminRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Softcorp.ConnectAdminRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Softcorp.ConnectAdminRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Softcorp.ConnectAdminRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    app: (f = msg.getApp()) && proto.Softcorp.ClientApp.toObject(includeInstance, f),
    overwriteid: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    timespan: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Softcorp.ConnectAdminRequest}
 */
proto.Softcorp.ConnectAdminRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Softcorp.ConnectAdminRequest;
  return proto.Softcorp.ConnectAdminRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Softcorp.ConnectAdminRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Softcorp.ConnectAdminRequest}
 */
proto.Softcorp.ConnectAdminRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.Softcorp.ClientApp;
      reader.readMessage(value,proto.Softcorp.ClientApp.deserializeBinaryFromReader);
      msg.setApp(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setOverwriteid(value);
      break;
    case 3:
      var value = /** @type {!proto.Softcorp.Timespan} */ (reader.readEnum());
      msg.setTimespan(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Softcorp.ConnectAdminRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Softcorp.ConnectAdminRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Softcorp.ConnectAdminRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Softcorp.ConnectAdminRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getApp();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.Softcorp.ClientApp.serializeBinaryToWriter
    );
  }
  f = message.getOverwriteid();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getTimespan();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * optional ClientApp app = 1;
 * @return {?proto.Softcorp.ClientApp}
 */
proto.Softcorp.ConnectAdminRequest.prototype.getApp = function() {
  return /** @type{?proto.Softcorp.ClientApp} */ (
    jspb.Message.getWrapperField(this, proto.Softcorp.ClientApp, 1));
};


/**
 * @param {?proto.Softcorp.ClientApp|undefined} value
 * @return {!proto.Softcorp.ConnectAdminRequest} returns this
*/
proto.Softcorp.ConnectAdminRequest.prototype.setApp = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Softcorp.ConnectAdminRequest} returns this
 */
proto.Softcorp.ConnectAdminRequest.prototype.clearApp = function() {
  return this.setApp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Softcorp.ConnectAdminRequest.prototype.hasApp = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool overwriteId = 2;
 * @return {boolean}
 */
proto.Softcorp.ConnectAdminRequest.prototype.getOverwriteid = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Softcorp.ConnectAdminRequest} returns this
 */
proto.Softcorp.ConnectAdminRequest.prototype.setOverwriteid = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional Timespan timespan = 3;
 * @return {!proto.Softcorp.Timespan}
 */
proto.Softcorp.ConnectAdminRequest.prototype.getTimespan = function() {
  return /** @type {!proto.Softcorp.Timespan} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.Softcorp.Timespan} value
 * @return {!proto.Softcorp.ConnectAdminRequest} returns this
 */
proto.Softcorp.ConnectAdminRequest.prototype.setTimespan = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


