// source: softcorp.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.Softcorp.PublicDashboardResponse');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Map');
goog.require('jspb.Message');
goog.require('proto.Softcorp.ClientApp');
goog.require('proto.Softcorp.Collaboration');
goog.require('proto.Softcorp.ConnectMetrics');
goog.require('proto.Softcorp.Organization');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Softcorp.PublicDashboardResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Softcorp.PublicDashboardResponse.repeatedFields_, null);
};
goog.inherits(proto.Softcorp.PublicDashboardResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Softcorp.PublicDashboardResponse.displayName = 'proto.Softcorp.PublicDashboardResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Softcorp.PublicDashboardResponse.repeatedFields_ = [2,4,7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Softcorp.PublicDashboardResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.Softcorp.PublicDashboardResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Softcorp.PublicDashboardResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Softcorp.PublicDashboardResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    organization: (f = msg.getOrganization()) && proto.Softcorp.Organization.toObject(includeInstance, f),
    organizationsList: jspb.Message.toObjectList(msg.getOrganizationsList(),
    proto.Softcorp.Organization.toObject, includeInstance),
    collaboration: (f = msg.getCollaboration()) && proto.Softcorp.Collaboration.toObject(includeInstance, f),
    collaborationsList: jspb.Message.toObjectList(msg.getCollaborationsList(),
    proto.Softcorp.Collaboration.toObject, includeInstance),
    secret: jspb.Message.getFieldWithDefault(msg, 5, ""),
    connectapp: (f = msg.getConnectapp()) && proto.Softcorp.ClientApp.toObject(includeInstance, f),
    connectappsList: jspb.Message.toObjectList(msg.getConnectappsList(),
    proto.Softcorp.ClientApp.toObject, includeInstance),
    metricsMap: (f = msg.getMetricsMap()) ? f.toObject(includeInstance, proto.Softcorp.ConnectMetrics.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Softcorp.PublicDashboardResponse}
 */
proto.Softcorp.PublicDashboardResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Softcorp.PublicDashboardResponse;
  return proto.Softcorp.PublicDashboardResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Softcorp.PublicDashboardResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Softcorp.PublicDashboardResponse}
 */
proto.Softcorp.PublicDashboardResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.Softcorp.Organization;
      reader.readMessage(value,proto.Softcorp.Organization.deserializeBinaryFromReader);
      msg.setOrganization(value);
      break;
    case 2:
      var value = new proto.Softcorp.Organization;
      reader.readMessage(value,proto.Softcorp.Organization.deserializeBinaryFromReader);
      msg.addOrganizations(value);
      break;
    case 3:
      var value = new proto.Softcorp.Collaboration;
      reader.readMessage(value,proto.Softcorp.Collaboration.deserializeBinaryFromReader);
      msg.setCollaboration(value);
      break;
    case 4:
      var value = new proto.Softcorp.Collaboration;
      reader.readMessage(value,proto.Softcorp.Collaboration.deserializeBinaryFromReader);
      msg.addCollaborations(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setSecret(value);
      break;
    case 6:
      var value = new proto.Softcorp.ClientApp;
      reader.readMessage(value,proto.Softcorp.ClientApp.deserializeBinaryFromReader);
      msg.setConnectapp(value);
      break;
    case 7:
      var value = new proto.Softcorp.ClientApp;
      reader.readMessage(value,proto.Softcorp.ClientApp.deserializeBinaryFromReader);
      msg.addConnectapps(value);
      break;
    case 8:
      var value = msg.getMetricsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt32, jspb.BinaryReader.prototype.readMessage, proto.Softcorp.ConnectMetrics.deserializeBinaryFromReader, 0, new proto.Softcorp.ConnectMetrics());
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Softcorp.PublicDashboardResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Softcorp.PublicDashboardResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Softcorp.PublicDashboardResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Softcorp.PublicDashboardResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOrganization();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.Softcorp.Organization.serializeBinaryToWriter
    );
  }
  f = message.getOrganizationsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.Softcorp.Organization.serializeBinaryToWriter
    );
  }
  f = message.getCollaboration();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.Softcorp.Collaboration.serializeBinaryToWriter
    );
  }
  f = message.getCollaborationsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.Softcorp.Collaboration.serializeBinaryToWriter
    );
  }
  f = message.getSecret();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getConnectapp();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.Softcorp.ClientApp.serializeBinaryToWriter
    );
  }
  f = message.getConnectappsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      proto.Softcorp.ClientApp.serializeBinaryToWriter
    );
  }
  f = message.getMetricsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(8, writer, jspb.BinaryWriter.prototype.writeInt32, jspb.BinaryWriter.prototype.writeMessage, proto.Softcorp.ConnectMetrics.serializeBinaryToWriter);
  }
};


/**
 * optional Organization organization = 1;
 * @return {?proto.Softcorp.Organization}
 */
proto.Softcorp.PublicDashboardResponse.prototype.getOrganization = function() {
  return /** @type{?proto.Softcorp.Organization} */ (
    jspb.Message.getWrapperField(this, proto.Softcorp.Organization, 1));
};


/**
 * @param {?proto.Softcorp.Organization|undefined} value
 * @return {!proto.Softcorp.PublicDashboardResponse} returns this
*/
proto.Softcorp.PublicDashboardResponse.prototype.setOrganization = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Softcorp.PublicDashboardResponse} returns this
 */
proto.Softcorp.PublicDashboardResponse.prototype.clearOrganization = function() {
  return this.setOrganization(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Softcorp.PublicDashboardResponse.prototype.hasOrganization = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Organization organizations = 2;
 * @return {!Array<!proto.Softcorp.Organization>}
 */
proto.Softcorp.PublicDashboardResponse.prototype.getOrganizationsList = function() {
  return /** @type{!Array<!proto.Softcorp.Organization>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Softcorp.Organization, 2));
};


/**
 * @param {!Array<!proto.Softcorp.Organization>} value
 * @return {!proto.Softcorp.PublicDashboardResponse} returns this
*/
proto.Softcorp.PublicDashboardResponse.prototype.setOrganizationsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.Softcorp.Organization=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Softcorp.Organization}
 */
proto.Softcorp.PublicDashboardResponse.prototype.addOrganizations = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.Softcorp.Organization, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Softcorp.PublicDashboardResponse} returns this
 */
proto.Softcorp.PublicDashboardResponse.prototype.clearOrganizationsList = function() {
  return this.setOrganizationsList([]);
};


/**
 * optional Collaboration collaboration = 3;
 * @return {?proto.Softcorp.Collaboration}
 */
proto.Softcorp.PublicDashboardResponse.prototype.getCollaboration = function() {
  return /** @type{?proto.Softcorp.Collaboration} */ (
    jspb.Message.getWrapperField(this, proto.Softcorp.Collaboration, 3));
};


/**
 * @param {?proto.Softcorp.Collaboration|undefined} value
 * @return {!proto.Softcorp.PublicDashboardResponse} returns this
*/
proto.Softcorp.PublicDashboardResponse.prototype.setCollaboration = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Softcorp.PublicDashboardResponse} returns this
 */
proto.Softcorp.PublicDashboardResponse.prototype.clearCollaboration = function() {
  return this.setCollaboration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Softcorp.PublicDashboardResponse.prototype.hasCollaboration = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated Collaboration collaborations = 4;
 * @return {!Array<!proto.Softcorp.Collaboration>}
 */
proto.Softcorp.PublicDashboardResponse.prototype.getCollaborationsList = function() {
  return /** @type{!Array<!proto.Softcorp.Collaboration>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Softcorp.Collaboration, 4));
};


/**
 * @param {!Array<!proto.Softcorp.Collaboration>} value
 * @return {!proto.Softcorp.PublicDashboardResponse} returns this
*/
proto.Softcorp.PublicDashboardResponse.prototype.setCollaborationsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.Softcorp.Collaboration=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Softcorp.Collaboration}
 */
proto.Softcorp.PublicDashboardResponse.prototype.addCollaborations = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.Softcorp.Collaboration, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Softcorp.PublicDashboardResponse} returns this
 */
proto.Softcorp.PublicDashboardResponse.prototype.clearCollaborationsList = function() {
  return this.setCollaborationsList([]);
};


/**
 * optional string secret = 5;
 * @return {string}
 */
proto.Softcorp.PublicDashboardResponse.prototype.getSecret = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.Softcorp.PublicDashboardResponse} returns this
 */
proto.Softcorp.PublicDashboardResponse.prototype.setSecret = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional ClientApp connectApp = 6;
 * @return {?proto.Softcorp.ClientApp}
 */
proto.Softcorp.PublicDashboardResponse.prototype.getConnectapp = function() {
  return /** @type{?proto.Softcorp.ClientApp} */ (
    jspb.Message.getWrapperField(this, proto.Softcorp.ClientApp, 6));
};


/**
 * @param {?proto.Softcorp.ClientApp|undefined} value
 * @return {!proto.Softcorp.PublicDashboardResponse} returns this
*/
proto.Softcorp.PublicDashboardResponse.prototype.setConnectapp = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Softcorp.PublicDashboardResponse} returns this
 */
proto.Softcorp.PublicDashboardResponse.prototype.clearConnectapp = function() {
  return this.setConnectapp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Softcorp.PublicDashboardResponse.prototype.hasConnectapp = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * repeated ClientApp connectApps = 7;
 * @return {!Array<!proto.Softcorp.ClientApp>}
 */
proto.Softcorp.PublicDashboardResponse.prototype.getConnectappsList = function() {
  return /** @type{!Array<!proto.Softcorp.ClientApp>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Softcorp.ClientApp, 7));
};


/**
 * @param {!Array<!proto.Softcorp.ClientApp>} value
 * @return {!proto.Softcorp.PublicDashboardResponse} returns this
*/
proto.Softcorp.PublicDashboardResponse.prototype.setConnectappsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.Softcorp.ClientApp=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Softcorp.ClientApp}
 */
proto.Softcorp.PublicDashboardResponse.prototype.addConnectapps = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.Softcorp.ClientApp, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Softcorp.PublicDashboardResponse} returns this
 */
proto.Softcorp.PublicDashboardResponse.prototype.clearConnectappsList = function() {
  return this.setConnectappsList([]);
};


/**
 * map<int32, ConnectMetrics> metrics = 8;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,!proto.Softcorp.ConnectMetrics>}
 */
proto.Softcorp.PublicDashboardResponse.prototype.getMetricsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,!proto.Softcorp.ConnectMetrics>} */ (
      jspb.Message.getMapField(this, 8, opt_noLazyCreate,
      proto.Softcorp.ConnectMetrics));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.Softcorp.PublicDashboardResponse} returns this
 */
proto.Softcorp.PublicDashboardResponse.prototype.clearMetricsMap = function() {
  this.getMetricsMap().clear();
  return this;};


