// source: softcorp.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.Softcorp.Ssn');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.Softcorp.SsnProvider');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Softcorp.Ssn = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Softcorp.Ssn, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Softcorp.Ssn.displayName = 'proto.Softcorp.Ssn';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Softcorp.Ssn.prototype.toObject = function(opt_includeInstance) {
  return proto.Softcorp.Ssn.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Softcorp.Ssn} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Softcorp.Ssn.toObject = function(includeInstance, msg) {
  var f, obj = {
    ssn: jspb.Message.getFieldWithDefault(msg, 1, ""),
    ssnhash: jspb.Message.getFieldWithDefault(msg, 2, ""),
    ssnidentifier: jspb.Message.getFieldWithDefault(msg, 3, ""),
    ssnprovider: (f = msg.getSsnprovider()) && proto.Softcorp.SsnProvider.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Softcorp.Ssn}
 */
proto.Softcorp.Ssn.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Softcorp.Ssn;
  return proto.Softcorp.Ssn.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Softcorp.Ssn} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Softcorp.Ssn}
 */
proto.Softcorp.Ssn.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSsn(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSsnhash(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSsnidentifier(value);
      break;
    case 4:
      var value = new proto.Softcorp.SsnProvider;
      reader.readMessage(value,proto.Softcorp.SsnProvider.deserializeBinaryFromReader);
      msg.setSsnprovider(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Softcorp.Ssn.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Softcorp.Ssn.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Softcorp.Ssn} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Softcorp.Ssn.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSsn();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSsnhash();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSsnidentifier();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getSsnprovider();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.Softcorp.SsnProvider.serializeBinaryToWriter
    );
  }
};


/**
 * optional string ssn = 1;
 * @return {string}
 */
proto.Softcorp.Ssn.prototype.getSsn = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Softcorp.Ssn} returns this
 */
proto.Softcorp.Ssn.prototype.setSsn = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string ssnHash = 2;
 * @return {string}
 */
proto.Softcorp.Ssn.prototype.getSsnhash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Softcorp.Ssn} returns this
 */
proto.Softcorp.Ssn.prototype.setSsnhash = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string ssnIdentifier = 3;
 * @return {string}
 */
proto.Softcorp.Ssn.prototype.getSsnidentifier = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Softcorp.Ssn} returns this
 */
proto.Softcorp.Ssn.prototype.setSsnidentifier = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional SsnProvider ssnProvider = 4;
 * @return {?proto.Softcorp.SsnProvider}
 */
proto.Softcorp.Ssn.prototype.getSsnprovider = function() {
  return /** @type{?proto.Softcorp.SsnProvider} */ (
    jspb.Message.getWrapperField(this, proto.Softcorp.SsnProvider, 4));
};


/**
 * @param {?proto.Softcorp.SsnProvider|undefined} value
 * @return {!proto.Softcorp.Ssn} returns this
*/
proto.Softcorp.Ssn.prototype.setSsnprovider = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Softcorp.Ssn} returns this
 */
proto.Softcorp.Ssn.prototype.clearSsnprovider = function() {
  return this.setSsnprovider(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Softcorp.Ssn.prototype.hasSsnprovider = function() {
  return jspb.Message.getField(this, 4) != null;
};


