// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package softcorp_network

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NetworkServiceClient is the client API for NetworkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetworkServiceClient interface {
	Heartbeat(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Invite(ctx context.Context, in *NetworkServiceRequest, opts ...grpc.CallOption) (*NetworkServiceResponse, error)
	Accept(ctx context.Context, in *NetworkServiceRequest, opts ...grpc.CallOption) (*NetworkServiceResponse, error)
	GetConnections(ctx context.Context, in *NetworkServiceRequest, opts ...grpc.CallOption) (*NetworkServiceResponse, error)
	Remove(ctx context.Context, in *NetworkServiceRequest, opts ...grpc.CallOption) (*NetworkServiceResponse, error)
}

type networkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkServiceClient(cc grpc.ClientConnInterface) NetworkServiceClient {
	return &networkServiceClient{cc}
}

func (c *networkServiceClient) Heartbeat(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/SoftcorpNetwork.NetworkService/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) Invite(ctx context.Context, in *NetworkServiceRequest, opts ...grpc.CallOption) (*NetworkServiceResponse, error) {
	out := new(NetworkServiceResponse)
	err := c.cc.Invoke(ctx, "/SoftcorpNetwork.NetworkService/Invite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) Accept(ctx context.Context, in *NetworkServiceRequest, opts ...grpc.CallOption) (*NetworkServiceResponse, error) {
	out := new(NetworkServiceResponse)
	err := c.cc.Invoke(ctx, "/SoftcorpNetwork.NetworkService/Accept", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) GetConnections(ctx context.Context, in *NetworkServiceRequest, opts ...grpc.CallOption) (*NetworkServiceResponse, error) {
	out := new(NetworkServiceResponse)
	err := c.cc.Invoke(ctx, "/SoftcorpNetwork.NetworkService/GetConnections", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) Remove(ctx context.Context, in *NetworkServiceRequest, opts ...grpc.CallOption) (*NetworkServiceResponse, error) {
	out := new(NetworkServiceResponse)
	err := c.cc.Invoke(ctx, "/SoftcorpNetwork.NetworkService/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkServiceServer is the server API for NetworkService service.
// All implementations should embed UnimplementedNetworkServiceServer
// for forward compatibility
type NetworkServiceServer interface {
	Heartbeat(context.Context, *Request) (*Response, error)
	Invite(context.Context, *NetworkServiceRequest) (*NetworkServiceResponse, error)
	Accept(context.Context, *NetworkServiceRequest) (*NetworkServiceResponse, error)
	GetConnections(context.Context, *NetworkServiceRequest) (*NetworkServiceResponse, error)
	Remove(context.Context, *NetworkServiceRequest) (*NetworkServiceResponse, error)
}

// UnimplementedNetworkServiceServer should be embedded to have forward compatible implementations.
type UnimplementedNetworkServiceServer struct {
}

func (UnimplementedNetworkServiceServer) Heartbeat(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedNetworkServiceServer) Invite(context.Context, *NetworkServiceRequest) (*NetworkServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invite not implemented")
}
func (UnimplementedNetworkServiceServer) Accept(context.Context, *NetworkServiceRequest) (*NetworkServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Accept not implemented")
}
func (UnimplementedNetworkServiceServer) GetConnections(context.Context, *NetworkServiceRequest) (*NetworkServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConnections not implemented")
}
func (UnimplementedNetworkServiceServer) Remove(context.Context, *NetworkServiceRequest) (*NetworkServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}

// UnsafeNetworkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkServiceServer will
// result in compilation errors.
type UnsafeNetworkServiceServer interface {
	mustEmbedUnimplementedNetworkServiceServer()
}

func RegisterNetworkServiceServer(s grpc.ServiceRegistrar, srv NetworkServiceServer) {
	s.RegisterService(&NetworkService_ServiceDesc, srv)
}

func _NetworkService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SoftcorpNetwork.NetworkService/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).Heartbeat(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_Invite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).Invite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SoftcorpNetwork.NetworkService/Invite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).Invite(ctx, req.(*NetworkServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_Accept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).Accept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SoftcorpNetwork.NetworkService/Accept",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).Accept(ctx, req.(*NetworkServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_GetConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).GetConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SoftcorpNetwork.NetworkService/GetConnections",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).GetConnections(ctx, req.(*NetworkServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SoftcorpNetwork.NetworkService/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).Remove(ctx, req.(*NetworkServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NetworkService_ServiceDesc is the grpc.ServiceDesc for NetworkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetworkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SoftcorpNetwork.NetworkService",
	HandlerType: (*NetworkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _NetworkService_Heartbeat_Handler,
		},
		{
			MethodName: "Invite",
			Handler:    _NetworkService_Invite_Handler,
		},
		{
			MethodName: "Accept",
			Handler:    _NetworkService_Accept_Handler,
		},
		{
			MethodName: "GetConnections",
			Handler:    _NetworkService_GetConnections_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _NetworkService_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "softcorp_network.proto",
}
