name: Build, Test and Deploy

on:
  push:
    tags:
      - "*"

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Get tag
        id: tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

      - name: Set pubdev tag
        run: sh update-pubdev-version.sh ${{ steps.tag.outputs.VERSION }}

      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.PUB_DEV_CREDENTIAL_JSON }}
          skip_test: true
          flutter_package: false
          package_directory: ./dart_softcorp
